### ISSUE TITLE
Possibility to use Onnx export format

### ISSUE THREAD

**Issue by JakubRudzki** [Bilot/AI-jack-opensource-R#18]
**Is your feature request related to a problem? Please describe.**
Current AI-JACK is not able to export models to external format used in many solutions. We should consider https://onnx.ai/ or similar open format.

**Comment by JedrzejFurmann** [comment]
**Update**: I think currently there is no possibility to export models as ONNX in R.

There is, however, a library in Python dedicated to onnx format and AI-JACK models made in H2O can be easily exported as onnx in Python.

**Comment by JakubRudzki** [comment]
Based on the comments it isn't possible right now to implement.
